drop table booking if exists;
drop table category if exists;
drop table option if exists;
drop table room if exists;
drop table room_option if exists;
drop table user if exists;

create table category (
  id bigint not null,
  name varchar(255) not null,
  primary key (id));

create table option (
  id bigint not null,
  name varchar(255) not null,
  price decimal(19,2) not null,
  primary key (id));

create table user (
  id bigint generated by default as identity,
  email varchar(255) not null,
  name varchar(255) not null,
  primary key (id));

create table room (
  id bigint not null,
  number integer not null,
  price decimal(19,2) not null,
  category_id bigint not null,
  primary key (id),
  foreign key (category_id) references category(id));

create table booking (
  id bigint generated by default as identity,
  end_date date not null,
  start_date date not null,
  room_id bigint not null,
  user_id bigint not null,
  primary key (id),
  foreign key (room_id) references room (id),
  foreign key (user_id) references user (id));

create table room_option (
  room_id bigint not null,
  option_id bigint not null,
  foreign key (option_id) references option(id),
  foreign key (room_id) references room(id));


